# Generated by Django 4.1 on 2022-08-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='assing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('typeProduc', models.CharField(max_length=50)),
                ('system', models.CharField(max_length=50)),
                ('ownerName', models.CharField(max_length=70)),
                ('ownerEmail', models.EmailField(max_length=254)),
                ('date', models.DateField()),
            ],
        ),
    ]
