# Generated by Django 4.1 on 2022-08-11 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devcoApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='assing',
        ),
    ]
